---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)

data("rest_inspec")
janitor::clean_names(rest_inspec)
rest_inspec = rest_inspec %>% 
  filter(grade != "NA" & zipcode == "10001" & grade != "Not Yet Graded")
rest_inspec = rest_inspec[order(rest_inspec$building),]
common_street =
  rest_inspec %>% 
  count(street, sort = TRUE) %>% 
  top_n(8) %>% 
  select(street)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart A

```{r}
rest_inspec %>%
  mutate(text_label = str_c("Score: ", score, '\nGrade: ', grade)) %>% 
  plot_ly(
    x = ~street, y = ~building, type = "scatter", mode = "markers",
    color = ~score, text = ~text_label, alpha = 0.5)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart B

```{r}
inner_join(rest_inspec, common_street, by = "street") %>% 
  mutate(street = fct_reorder(street, score)) %>% 
  plot_ly(y = ~score, color = ~street, type = "box",
          colors = "Set2")
```

### Chart C

```{r}
rest_inspec %>% 
  count(street) %>% 
  mutate(street = fct_reorder(street, n)) %>% 
  plot_ly(x = ~street, y = ~n, color = ~street, type = "bar")
```

